---
- hosts: all
  become: yes
  remote_user: ubuntu
  become_user: root
  vars:
  - terraform_version: "1.0.9"

  tasks:

  - name: Update system
    shell: apt-get update

  - name: Install unzip to unarchive terraform
    apt:
      name: unzip
      state: present

  - name: Download terraform archive Linux 64 bits
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
      dest: /tmp/terraform-{{ terraform_version }}.zip

  - name: Unarchive terraform binnary to user path
    unarchive:
      src: /tmp/terraform-{{ terraform_version }}.zip
      dest: /usr/bin/
      remote_src: yes